# Watcher

![CI Status](https://github.com/wilhelm-murdoch/go-watcher/actions/workflows/ci.yml/badge.svg)
[![GoDoc](https://godoc.org/github.com/wilhelm-murdoch/go-watcher?status.svg)](https://pkg.go.dev/github.com/wilhelm-murdoch/go-watcher)
[![Go report](https://goreportcard.com/badge/github.com/wilhelm-murdoch/go-watcher)](https://goreportcard.com/report/github.com/wilhelm-murdoch/go-watcher)
[![Stability: Experimental](https://masterminds.github.io/stability/experimental.svg)](https://masterminds.github.io/stability/experimental.html)

A no-nonsense wrapper around the [fsnotify](https://pkg.go.dev/github.com/fsnotify/fsnotify) package.

## Install
```
$ go get github.com/wilhelm-murdoch/go-watcher
```

# Reference

{{ range . }}{{ range .Files.Items }}{{ range .Functions.Items }}{{ if and (.IsExported) (ne .Name "main") (not .IsTest) (not .IsExample) (not .IsBenchmark)}}* [{{ .Name }}](#Function-{{ .Name }})
{{ end }}{{ end }}{{ end }}{{ end }}

{{ range . }}{{ range .Files.Items }}{{ $path := .Path }}{{ range .Functions.Items }}{{ if and (.IsExported) (ne .Name "main") (not .IsTest) (not .IsExample) (not .IsBenchmark)}}### Function `{{ .Name }}`
* `{{ trim .Signature }}` [#]({{ $path }}#L{{ .LineStart }})
* `{{ $path }}:{{ .LineStart }}:{{ .LineEnd }}` [#]({{ $path }}#L{{ .LineStart }}-L{{ .LineEnd }})

{{ .Doc | replace "\n" " " }}
{{ range .Examples.Items }}
```go
package main

import (
  "fmt"
  "strings"

  "github.com/wilhelm-murdoch/go-play"
)

func main() {
{{ indent 4 .Body }}
}
```
{{ if .Output }}```go
{{ .Output }}
```{{ end }}{{ end }}
{{ end }}{{ end }}{{ end }}{{ end }}

Documentation generated by [Gadget](https://github.com/wilhelm-murdoch/go-gadget).

# License
Copyright © {{ now | date "2006" }} [Wilhelm Murdoch](https://wilhelm.codes).

This project is [MIT](./LICENSE) licensed.